### PR TITLE
Testing struct functionality for the Cell class in cell/cell.py

### PR DESCRIPTION
**Pull request by suhasks123**
- Added serialize and deserialize functions in cell/serializers.py.
- Added extra class variable for Cell class to enable this feature.

Needs changes to parsing functions in cell/cell_processing.py for deserialize function to work. Also needs an extra class variable in all cell classes for storing format string for the struct

### CODE REVIEW

**Comment by NJnisarg** [comment]
@suhasks123 The format string param needs to have a default value of None so that it does not break the code. Also, make a setter function to set a format string on cell object.
Also make a standard python dict that has a mapping for cell type and corresponding cell format string, we should be using this dict as a lookup for fetching a format string for a cell type and use the setter function

**Comment by suhasks123** [comment]
> @suhasks123 The format string param needs to have a default value of None so that it does not break the code. Also, make a setter function to set a format string on cell object.
> Also make a standard python dict that has a mapping for cell type and corresponding cell format string, we should be using this dict as a lookup for fetching a format string for a cell type and use the setter function

The class variables for the format strings are not necessary when we create the dictionary right? It can directly be looked up from the dict when we need it. Also, the sizes will not be accurate if we implement a dictionary for the format strings since a lot of class variables are of the size specified in another class variable (for example, HDATA is of length HLEN in Create cell). I think it's not a problem if I assume the sizes provided in the spec since it'll be usually more than the data but just wanted to let you know.

**Comment by suhasks123** [comment]
Also, I'm not sure of what the setter function actually does. Does it create the format string to be added to the dictionary?

**Comment by NJnisarg** [comment]
This functionality has been implemented. I will close the PR

**Pull request closed without merging**
